#!/bin/sh
set -e

case "$1" in
    configure)
	user="zalando"
	group="zalando"
	datadir="/server/appdynamics"

	if ! getent group "$group" > /dev/null 2>&1 ; then
	    addgroup --system "$group" --gid 907 --quiet 
	fi

	if ! id "$user" > /dev/null 2>&1 ; then
	    adduser --system --home "/home/$user" --uid 907 --no-create-home \
		--ingroup "$group" --disabled-password \
		--shell /bin/bash "$user"
	fi

	install -d -o "$user" -g "$group" -m 0755 "$datadir"
    ;;
esac
