#!/bin/sh
set -e

case "$1" in
    configure)
    user="zalando"
    group="zalando"
    id=907
    datadir="/server/appdynamics"

    if ! getent group "$group" > /dev/null 2>&1 ; then
        addgroup --system "$group" \
                 --gid $id \
                 --quiet 
    fi

    if ! id "$user" > /dev/null 2>&1 ; then
        adduser --system \
                --home "/home/$user" \
                --uid $id --no-create-home \
                --ingroup "$group" \
                --disabled-password \
                --shell /bin/bash "$user"
    fi

    install -d -o "$user" -g "$group" -m 0755 "$datadir"
    chown -R "$user"."$group" "$datadir"/*

    ;;
esac
